/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BoxColor: typeof import('./src/components/BoxColor.vue')['default']
    Button: typeof import('primevue/button')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    Guess: typeof import('./src/components/Guess.vue')['default']
    GuessInput: typeof import('./src/components/GuessInput.vue')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
